### ISSUE TITLE
Share your project on PCBWay

### ISSUE THREAD

**Issue by kalgon** [necroware/nwX287#1]
Hi,

Could you share your project directly on PCBWay (https://www.pcbway.com/project/shareproject/) ?

It would be easier to order PCBs and you could get some money too ;-)

Regards,
Xavier

**Comment by necroware** [comment]
Hi Xavier,

may be one day. I don't want to spread my projects all over the place, it makes it harder to maintain them and keep the versions up to day. I mean PCB Way is not the only one manufacturer. I'm also currently not registered on PCB Way and I don't think that I will get a lot of money from it anyway. I'll keep this request open for now, may be I'll change my mind one day.

However, it is currently super easy as well. I guess, everybody is able to drag and drop a file and if not, probably, my projects are not the right thing :D

Cheers,
Filipp
