### ISSUE TITLE
DS1386-8K-120

### ISSUE THREAD

**Issue by toncho11** [necroware/nwX287#14]
Does it replace DS1386-8K-120 or DS1386-8K-150 ?
These have 8KB of NVRAM.

**Comment by necroware** [comment]
No, the compatible models are listed on the project site.

**Comment by drencorxeen** [comment]
> Does it replace DS1386-8K-120 or DS1386-8K-150 ? These have 8KB of NVRAM.

Based on the chip you listed and you stated is 8K of NVRAM.

The bq3285 & bq4285 both have only 114 bytes of general nonvolatile
storage.

So based on just the NVRAM size alone, I would say probably not.
