### ISSUE TITLE
CMOS Inoperational after some boots

### ISSUE THREAD

**Issue by leonpierre** [necroware/nwX287#15]
The first bootup's are fine but then I always get this "CMOS Inoperational - System halted" error. 
When I remove the battery (CR1220) for some time and reset it in the error is gone.

It is a replacement for a Dallas DS1287 in a 386-SX Laptop (Walkom / NoteStar NP-903).

The nwX287 uses a DS12885S RTC chip.

Any hints what could be wrong?

**Comment by necroware** [comment]
Most probably defective IC.

**Comment by necroware** [comment]
Cool!
