### ISSUE TITLE
Please add pin 1 silkscreen markings for the clock chip

### ISSUE THREAD

**Issue by feltel** [necroware/nwX287#17]
Recently I have had produced some PCBs using your fantasic dallas clock module replacements. I'm now in the process of assembling one module. It seems there is no (identifieable) pin 1 marking on the silkscreen for the clock chip. Looking around it seems that pin 1 is towards the crystal. To make thinks clear please add a marking on the silkscreen.

![PXL_20231230_102734983](https://github.com/necroware/nwX287/assets/264706/d085212e-badb-4bcd-86a2-c4da1e7ab6c5)

Thanks alot and have a nice 2024.

**Comment by necroware** [comment]
The pin one is already marked by the footprint of the library. There is no need to add own markings.

![image](https://github.com/necroware/nwX287/assets/75118326/2ccf9786-67a2-43b8-a9b6-48f027322b51)
