### ISSUE TITLE
Implementing DS1643 suppoort

### ISSUE THREAD

**Issue by Deftaudio** [necroware/nwX287#20]
Hi, just wondering if there is any way to implement DS1643 support which is 8k device?

**Comment by necroware** [comment]
H, this is a completely different module. This project is to replace DS12887 and compatible modules, so the question if something different can be implemented is kind of unrelated. Even if DS1643 is also an RTC module, it's still another one.

If you have your old module, may be this video can be helpful to you:
https://youtu.be/ecTZtZhE9bI

**Comment by Deftaudio** [comment]
I appreciate this, thank you, this video explains it very well.
