### ISSUE TITLE
Compatibility with Dallas DS14287

### ISSUE THREAD

**Issue by Deksor** [necroware/nwX287#3]
Hello !
Do you think it could work with the Dallas DS14287 ? I suspect the Benchmarq BQ4287 is a clone of that Dallas but I'm not 100% sure it's safe to try. Can you tell me ?
If it's safe I'll try it and report back :)

**Comment by necroware** [comment]
Hi Deksor! By the datasheets the DS14285 and BQ4285 are identical chips, just made by different companies. So I'm confident that they are interchangeable. You can use nwX287 either with Dallas or Benchmarq ICs, the last ones are just easier to find today.

**Comment by Deksor** [comment]
Nice !! I tested it and indeed, it works :)
Could you add it to your compatibility list ?

**Comment by necroware** [comment]
Thank you, I will.

**Comment by necroware** [comment]
Done
