### ISSUE TITLE
chips have the same code in kicad schematic

### ISSUE THREAD

**Issue by dataino-it** [necroware/nwX287#4]
![Untitled](https://user-images.githubusercontent.com/5722883/146086335-7bbfd534-1a3f-4285-9c2f-fa3a4598c466.png)
chips have the same code in kicad schematic

**Comment by necroware** [comment]
That's on purpose. The one represents the outer DIP and the other one the SO.

**Comment by dataino-it** [comment]
Yes, I understood by opening the pcb

**Comment by dataino-it** [comment]
can be. or 24 pin socket

**Comment by necroware** [comment]
I renamed it simply in socket ;)
