### ISSUE TITLE
Question about CR2025 vs 1225

### ISSUE THREAD

**Issue by atheros** [necroware/nwX287#5]
Hi,

Awesome job you did here, big thanks!

I want to order the components, but I see an issue. Readme calls for CR1220 / CR1225 battery holder while the silk screen layer has CR2025 marking.

So just to be sure, which is it? Or do all of those battery holders fit on the PCB?

Thanks!

**Comment by ndemarco** [comment]
![image](https://user-images.githubusercontent.com/6326614/146566796-f666e91f-f269-4fa0-b248-388bf4e7705b.png)

I'm seeing CR1220 in the silk layer.

The 2025 is a 20 mm diameter battery. The 12xx is a 12 mm diameter cell. They're not interchangeable.

**Comment by necroware** [comment]
See #6
