### ISSUE TITLE
Silk screen layer mentions CR2025 instead of CR1220/1225

### ISSUE THREAD

**Issue by atheros** [necroware/nwX287#6]
Hi,

Awesome job you did here, big thanks!

I want to order the components, but I see an issue. Readme calls for CR1220 / CR1225 battery holder while the silk screen layer has CR2025 marking.

So just to be sure, which is it? Or do all of those battery holders fit on the PCB?

Thanks!

**Comment by necroware** [comment]
Oh, that's a mistake on the silk screen layer. The batter (holder) must be CR1220 (CR1225 is the same size). I'll fix the silk screen layer and make a fixed release.

**Comment by necroware** [comment]
Fixed and release the new revision 1a:
https://github.com/necroware/nwX287/releases/tag/rev1a
