### ISSUE TITLE
Include the symbol cache

### ISSUE THREAD

**Issue by ndemarco** [necroware/nwX287#7]
I'm fairly new to KiCad. Actually, I just installed it. I do use Altium for work, though.

It seems the symbol cache is missing.
![image](https://user-images.githubusercontent.com/6326614/146567433-72dc8d8d-e4b2-4c03-ad16-825031c9a5a4.png)

**Comment by necroware** [comment]
Kicad generates the *-cache.lib file automatically. Please don't use KiCad 5.99, that is a development version and you will have many issues using that one. The current official version is 5.1.12

**Comment by necroware** [comment]
By the way, if you want just to order the PCBs, you don't need to use KiCad at all. Simply go into releases and download the gerber files, which you can use to make the order.  https://github.com/necroware/nwX287/releases

**Comment by ndemarco** [comment]
Thank you 2x today (not seeing ver 1.a, not seeing I installed KiCad
preview). I really must wake up! Your videos are great. Very well done,
precise and clear.

KiCad interests me, so I prefer to go that way.

**Comment by necroware** [comment]
done
