### ISSUE TITLE
Xtal

### ISSUE THREAD

**Issue by jcarval** [necroware/nwX287#9]
Hi, my friend, can I solder the crystal in any way or the xtal has a like + and - side like capacitors? (sorry my nob question about crystals)
I have ordered some from alliexpress and they some have no marking and the legs are the same size.
In the photos you supplied I can see that some lettering in them, but could be coincidence . 
Thank you!
Jorge

**Comment by necroware** [comment]
Hi Jorge! You can solder it either way, they don't have polarity.
Cheers!
